### ISSUE TITLE
Scheduled Event test in Site Health fails

### ISSUE THREAD

**Issue by gilbitron** [deliciousbrains/spinupwp-plugin#35]
A customer suggests we add the following to prevent this failure appearing as we set up a real cron in SpinupWP:

```
function spinup_remove_site_tests( $tests ) {
    unset( $tests['direct']['scheduled_events'] );
    eturn $tests;
}
add_filter( 'site_status_tests', ’spinup_remove_site_tests' ); 
```

**Comment by A5hleyRich** [comment]
I'm not sure disabling that test is a good idea. Although WP Cron is disabled, the events should still fire because of the Unix cron we configure. The `WP_Site_Health` does account for the use of the `DISABLE_WP_CRON` constant which increases the thresholds. If that test is failing, there's likely a problem and it should be flagged as such.

**Comment by A5hleyRich** [comment]
As per my previous comment, the scheduled event health check is still relevant. Closing.
